# Jupyter Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ''
author: Franklin Koch <franklin@curvenote.com>
logo: images/logo-wide.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/myst-spec # Online location of your book

# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  # favicon: images/favicon.ico
  # google_analytics_id: G-XXX or UA-XXX
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  extra_navbar: Written in <a href="https://curvenote.com">Curvenote</a>
